# using alpine image for development
FROM node:13.6-alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
RUN npm install

# Bundle source
COPY . .

CMD [ "npm", "run", "start:dev" ]